sonar.projectKey=aariiparekh3012-collab_limit-order-book-engine
sonar.organization=aariiparekh3012-collab

sonar.projectName=Limit Order Book Engine
sonar.projectVersion=0.1.0

sonar.sources=src,include,tools,bench
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build-wrapper-output/compile_commands.json
